// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlDGAh628aVmlnId2Q18keMM9eLew1TOs',
    appId: '1:638207962791:web:a5bc453796cb97e7e0b582',
    messagingSenderId: '638207962791',
    projectId: 'todoapp-ce82d',
    authDomain: 'todoapp-ce82d.firebaseapp.com',
    storageBucket: 'todoapp-ce82d.appspot.com',
    measurementId: 'G-P24M3S2W3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHZdegxgMDe9qpElUTyMEh1uH_K5_vyVs',
    appId: '1:638207962791:android:f1aa5626dd6f14e2e0b582',
    messagingSenderId: '638207962791',
    projectId: 'todoapp-ce82d',
    storageBucket: 'todoapp-ce82d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLSfq3U3ihosrs8Hhys0JbUq5Kw9YpKgw',
    appId: '1:638207962791:ios:1c373672123f494fe0b582',
    messagingSenderId: '638207962791',
    projectId: 'todoapp-ce82d',
    storageBucket: 'todoapp-ce82d.appspot.com',
    iosClientId:
        '638207962791-9qavit61mqi3n555nrgvt1qcod7h1kmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLSfq3U3ihosrs8Hhys0JbUq5Kw9YpKgw',
    appId: '1:638207962791:ios:1c373672123f494fe0b582',
    messagingSenderId: '638207962791',
    projectId: 'todoapp-ce82d',
    storageBucket: 'todoapp-ce82d.appspot.com',
    iosClientId:
        '638207962791-9qavit61mqi3n555nrgvt1qcod7h1kmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoFire',
  );
}
